version: "2"
services:
  docker-ps4-pkg-sender:
    image: docker-ps4-pkg-sender:latest
    container_name: docker-ps4-pkg-sender
    environment:
      - PORT=8080
      - STATIC_FILES=/pkg_sender/files
      - LOCALIP=localhost
      - PS4IP=ps4.ip
    restart: unless-stopped
    ports:
      - 7777:8080
    volumes:
      - ./files:/pkg_sender/files